server:
  port: 8082
  servlet:
    context-path: /notification
spring:
  application:
    name: notification
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest # Thứ tự cũ đến mới
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer #key
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer #value
      properties:
        spring.json.trusted.packages: "*"
# logging:
#   level:
#     org.springframework.kafka: DEBUG
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

resend:
  apiKey: "re_CxUq4nBh_ECnHuF8ML7jD7PKn65UZm6Lz"