networks:
  my-internal-net:
    driver: bridge

services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka-server
    networks:
      - my-internal-net
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      # Sửa localhost thành tên service 'kafka' HOẶC 'localhost' tùy vào cách Docker network map
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # THÊM DÒNG NÀY: Để bỏ qua kiểm tra số lượng bản sao (vì em chạy có 1 mình nó)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  # Số lượng broker mặc định là 3 thì mới nhận message
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0 # Thời gian chờ khi có consumer mới thêm. Mặc định là 3000ms
      # Hai dòng này quản lý việc Giao dịch (Transaction). Nó đảm bảo các tin nhắn gửi từ những hàm có @Transactional được quản lý an toàn.
      # Kafka mặc định đòi hỏi phải có ít nhất 3 bản sao (Replication Factor) và ít nhất 2 bản sao phải "sống"
      # (MIN_ISR - Minimum In-Sync Replicas) thì nó mới cho phép giao dịch thành công.
      # Khi gọi send kafka ở @Transactional, sẽ đợi tìm 2 Broker còn lại do ở đây chỉ 1 broker nên bị pending ko gửi đc message
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1