server:
  port: 8084
  servlet:
    context-path: /file
spring:
  application:
    name: file
  mongodb:
    uri: mongodb://root:root@localhost:27017/file-service?authSource=admin
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

app:
  file:
    storage-dir: D:/java-string-boot/bookteria-file
    download-prefix: http://localhost:8888/api/v1/file/media/download