server:
  port: 8084
  servlet:
    context-path: /file
spring:
  application:
    name: file
  mongodb:
    uri: mongodb://root:root@localhost:27017/file-service?authSource=admin
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"