spring:
  application:
    name: profile
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678
server:
  port: 8081
  servlet:
    context-path: /profile
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

app:
  service:
    file-service: "http://localhost:8084/file"