spring:
  application:
    name: profile
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678
server:
  port: 8081
  servlet:
    context-path: /profile
